# sqlite3 database file for the project
DB_FILE = "~/.top_cat/db"


# tar file that you'll be pulling down from http://download.tensorflow.org/models/ assuming you are using deeplabv3 for labelling (requires more than 1gb memory!)
## It's also possible to tweak it and use your own deeplab weights: just put the absolute path to the tgz
## other weights from the tensorflow models repo are also possible. Check deeplabv3 demo ipynb for more info
DEEPLABV3_FILE_NAME = "deeplabv3_pascal_train_aug_2018_01_04.tar.gz"


# If you are using google vision you need to set an environment variable for
#  GOOGLE_APPLICATION_CREDENTIALS _or_ you can configure this in your config.
#  Env var takes precedence over config, but calling top_cat.py via CRON means you won't have the env var set...
GOOGLE_APPLICATION_CREDENTIALS = "PATH_TO_YOUR_CONFIG_JSON"


# For top posts, look for these labels
LABELS_TO_SEARCH_FOR = ["cat","dog"]


# When looking through a video, how many frames to use for classification.
MAX_IMS_PER_VIDEO = 10

# How many top posts to bother processing? (Anything >= 1 is ok)
MAX_POSTS_TO_PROCESS = 10

# Sometimes the reddit api server fails the first time... actually it started working consistently recently so probably can get rid of this eventually.
MAX_REDDIT_API_ATTEMPTS = 20


# Choices are currently "deeplab" or "gvision_labeler".
# gvision_labeler (google vision api) uses minimal memory and can run on gcloud or aws free tier linux boxes (~$1/month api calls)
# deeplab is a tensorflow research model that requires more memory, so can't run on free tier servers
## You can also add a new model by adding a new python file into this directory that implements `get_labelling_func_given_config(config)`
MODEL_TO_USE = "deeplab"

# Set this variable to limit how many cores tensorflow can use.
# 0 -> use every core. N -> use N cores. -N -> Use all - N cores.
PROCS_TO_USE = "-1"

# If you want to post to a slack channel, follow instructions in README
POST_TO_SLACK_TF = false
SLACK_API_TOKEN = "YOUR__SLACK__API_TOKEN_GOES_HERE"
# Give one channel per label from LABELS_TO_SEARCH_FOR
SLACK_CHANNELS = ["#top_cat", "#top_dog"]


# If you want to post to facebook, then add your token. CURRENTLY BROKEN. FB changed their api and are much more strict about giving out tokens... I haven't bothered to fix FB posting yet. #FIXME: coming again at some point maybe
POST_TO_FB_TF = false
FB_PAGE_ACCESS_TOKEN = "YOUR__FB__PAGE_ACCESS_TOKEN_GOES_HERE"
