DB_FILE = "~/.top_cat/db"

# If you went to the trouble of training your own then just put the absolute path to the tar, other options from tensorflow are also possible. Check deeplabv3 demo ipynb for more info
DEEPLABV3_FILE_NAME = "deeplabv3_pascal_train_aug_2018_01_04.tar.gz"

LABELS_TO_SEARCH_FOR = ["cat","dog"]
MAX_REDDIT_API_ATTEMPTS = 20

POST_TO_FB_TF = false
FB_PAGE_ACCESS_TOKEN = "YOUR__FB__PAGE_ACCESS_TOKEN_GOES_HERE"

# https://api.slack.com/custom-integrations/legacy-tokens
POST_TO_SLACK_TF = false
SLACK_API_TOKEN = "YOUR__SLACK__API_TOKEN_GOES_HERE"
SLACK_CHANNEL = "#top_cat"
