DB_FILE = "~/.top_cat/db"

# If you went to the trouble of training your own then just put the absolute path to the tgz, other weights from the tensorflow models repo are also possible. Check deeplabv3 demo ipynb for more info
DEEPLABV3_FILE_NAME = "deeplabv3_pascal_train_aug_2018_01_04.tar.gz"

LABELS_TO_SEARCH_FOR = ["cat","dog"]
MAX_REDDIT_API_ATTEMPTS = 20

POST_TO_FB_TF = false
FB_PAGE_ACCESS_TOKEN = "YOUR__FB__PAGE_ACCESS_TOKEN_GOES_HERE"

# https://api.slack.com/custom-integrations/legacy-tokens
POST_TO_SLACK_TF = false
SLACK_API_TOKEN = "YOUR__SLACK__API_TOKEN_GOES_HERE"
# Give one channel for each label.
# If you want them all in the same channel then you might get reposts.
SLACK_CHANNELS = ["#top_cat", "#top_dog"]


# Set this to true if you want to skip using deeplabv3 and instead prefer using google vision.
USE_GOOGLE_VISION = false
